
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'E4A162725DE2FFAA083831295A587C0B'
    
_lr_action_items = {'SEPARADOR':([3,4,5,6,10,11,12,],[8,8,-7,-4,8,8,8,]),'DIGITO':([0,2,7,8,9,20,21,22,23,24,29,30,],[2,6,2,-6,2,-5,24,24,24,28,30,31,]),'$end':([1,25,26,27,31,],[0,-1,-3,-2,-9,]),'MES':([0,8,9,],[5,-6,5,]),'HORA':([28,],[29,]),'ANNO':([8,13,14,15,],[-6,17,17,17,]),'ESPACIO':([16,17,18,19,],[20,-8,20,20,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'A':([13,14,15,],[16,18,19,]),'C':([3,4,10,11,12,],[7,9,13,14,15,]),'P':([0,],[1,]),'H':([21,22,23,],[25,26,27,]),'M':([0,9,],[3,11,]),'E':([16,18,19,],[21,22,23,]),'D':([0,7,9,],[4,10,12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> P","S'",1,None,None,None),
  ('P -> M C D C A E H','P',7,'p_oceano_con_olas','proyecto.py',72),
  ('P -> D C D C A E H','P',7,'p_oceano_con_olas','proyecto.py',73),
  ('P -> D C M C A E H','P',7,'p_oceano_con_olas','proyecto.py',74),
  ('D -> DIGITO DIGITO','D',2,'p_doble_digito','proyecto.py',79),
  ('E -> ESPACIO','E',1,'p_espacio','proyecto.py',83),
  ('C -> SEPARADOR','C',1,'p_separador','proyecto.py',88),
  ('M -> MES','M',1,'p_mes','proyecto.py',93),
  ('A -> ANNO','A',1,'p_anno','proyecto.py',103),
  ('H -> DIGITO DIGITO HORA DIGITO DIGITO','H',5,'p_hora','proyecto.py',108),
]
