
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '799368C3AA81D9053D834B09AE18675B'
    
_lr_action_items = {'$end':([2,11,12,],[0,-3,-1,]),'SEPARADOR':([1,3,6,7,],[5,-5,5,-2,]),'ANNO':([5,8,],[-4,10,]),'ESPACIO':([9,10,],[11,-6,]),'MES':([0,],[3,]),'DIA':([4,5,],[7,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'C':([1,6,],[4,8,]),'M':([0,],[1,]),'A':([8,],[9,]),'fecha':([0,],[2,]),'D':([4,],[6,]),'E':([9,],[12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> fecha","S'",1,None,None,None),
  ('fecha -> M C D C A E','fecha',6,'p_oceano_con_olas','proyecto.py',72),
  ('D -> DIA','D',1,'p_dia','proyecto.py',77),
  ('E -> ESPACIO','E',1,'p_espacio','proyecto.py',82),
  ('C -> SEPARADOR','C',1,'p_separador','proyecto.py',87),
  ('M -> MES','M',1,'p_mes','proyecto.py',92),
  ('A -> ANNO','A',1,'p_anno','proyecto.py',96),
]
